# Generated by Django 3.0.6 on 2020-07-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerinfo_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='treasurex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='treasurey',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
