# Generated by Django 3.0.6 on 2020-07-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200709_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='creator',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
